NumPy is a library written for scientific computing and data analysis. It stands for numerical python.

The most basic object in NumPy is the ndarray, or simply an array, which is an n-dimensional, homogenous array. By homogenous, we mean that all the elements in a numpy array have to be of the same data type, which is commonly numeric (float or integer).

Let's see some examples of arrays.

In [2]:
# importing numpt array
import numpy as np

In [3]:
# Creating a 1-D array using a list
# np.array() takes in a list or a tuple as argument, and converts into an array
array_1d = np.array([2, 4, 5, 6, 7, 9])
print(array_1d)
print(type(array_1d))

[2 4 5 6 7 9]
<class 'numpy.ndarray'>


In [4]:
# Creating a 2-D array using two lists
array_2d = np.array([[2, 3, 4], [5, 8, 7]])
print(array_2d)

[[2 3 4]
 [5 8 7]]


In [5]:
list_1 = [3, 6, 7, 5]
list_2 = [4, 5, 1, 7]

# the list way to do it: map a function to the two lists
product_list = list(map(lambda x, y: x*y, list_1, list_2))
print(product_list)

[12, 30, 7, 35]


Different numpy commands

The following ways are commonly used ways to initialise numpy array:

np.ones(): Create array of 1s

np.zeros(): Create array of 0s

np.random.random(): Create array of random numbers

np.arange(): Create array with increments of a fixed step size

np.linspace(): Create array of fixed length

### np.ones()

In [6]:
o=np.ones(5)
print(o)

[1. 1. 1. 1. 1.]


In [9]:
o1=np.ones(5,dtype=int)
print(o1)

[1 1 1 1 1]


In [11]:
o2=np.ones((5,3))
print(o2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### np.zeros()

In [13]:
z1=np.zeros(5)
print(z1)

[0. 0. 0. 0. 0.]


In [14]:
z2=np.zeros((2,2),dtype=int)
print(z2)

[[0 0]
 [0 0]]


### np.random()

In [18]:
r=np.random.random()
print(r)

0.31783386184009843


In [20]:
r1=np.random.random((2,3))
print(r1)

[[0.22320287 0.56107483 0.0413814 ]
 [0.02205474 0.33888719 0.88170752]]


### np.arange()

In [21]:
ar1=np.arange(2,10)
print(ar1)

[2 3 4 5 6 7 8 9]


In [22]:
ar2=np.arange(2,10,2)
print(ar2)

[2 4 6 8]


### np.linspace()

In [24]:
# generating 25 numbers  from 10 to 13 
np.linspace(10,13,25)

array([10.   , 10.125, 10.25 , 10.375, 10.5  , 10.625, 10.75 , 10.875,
       11.   , 11.125, 11.25 , 11.375, 11.5  , 11.625, 11.75 , 11.875,
       12.   , 12.125, 12.25 , 12.375, 12.5  , 12.625, 12.75 , 12.875,
       13.   ])

Structure of array and content of array

shape: Shape of array (n x m)

dtype: data type (int, float etc.)

ndim: Number of dimensions (or axes)

itemsize: Memory used by each array elememnt in bytes

reshape : It changes the shape of the array

In [33]:
arr1=np.array(((5,4),(10,20)))
print(arr1)

[[ 5  4]
 [10 20]]


In [34]:
print(arr1.shape)

(2, 2)


In [35]:
print(arr1.dtype)

int32


In [36]:
print(arr1.ndim)

2


In [37]:
print(arr1.itemsize)

4


In [40]:
arr2=arr1.reshape(1,4)
print(arr2)

[[ 5  4 10 20]]


Stacking and Splitting Arrays

Stacking: np.hstack() and n.vstack()
    
Stacking is done using the np.hstack() and np.vstack() methods. For horizontal stacking, the number of rows should be the same, 
while for vertical stacking, the number of columns should be the same.

In [44]:
# Creating two arrays
array_1 = np.arange(12,24).reshape(3, 4)
array_2 = np.arange(20).reshape(5, 4)

print(array_1)
print("\n")
print(array_2)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [45]:
# vstack
# Note that np.vstack(a, b) throws an error - you need to pass the arrays as a list
np.vstack((array_1, array_2))

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [47]:
# Creating two arrays
array_1 = np.arange(12,24).reshape(3, 4)
array_2 = np.arange(12).reshape(3, 4)

print(array_1)
print("\n")
print(array_2)

print(np.vstack((array_1, array_2)))

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Numpy Mathematical Calculations

In [48]:
# Basic mathematical operations
a = np.arange(10, 20)
print(a)
# sin, cos, exp, log
print(np.sin(a))
print(np.cos(a))
print(np.exp(a))
print(np.log(a))

[10 11 12 13 14 15 16 17 18 19]
[-0.54402111 -0.99999021 -0.53657292  0.42016704  0.99060736  0.65028784
 -0.28790332 -0.96139749 -0.75098725  0.14987721]
[-0.83907153  0.0044257   0.84385396  0.90744678  0.13673722 -0.75968791
 -0.95765948 -0.27516334  0.66031671  0.98870462]
[2.20264658e+04 5.98741417e+04 1.62754791e+05 4.42413392e+05
 1.20260428e+06 3.26901737e+06 8.88611052e+06 2.41549528e+07
 6.56599691e+07 1.78482301e+08]
[2.30258509 2.39789527 2.48490665 2.56494936 2.63905733 2.7080502
 2.77258872 2.83321334 2.89037176 2.94443898]


Basic linear Algebra

In [53]:
a=np.array(np.arange(10,14,1).reshape(2,2))

In [54]:
print(a)

[[10 11]
 [12 13]]


In [55]:
np.linalg.inv(a)

array([[-6.5,  5.5],
       [ 6. , -5. ]])

In [56]:
np.linalg.det(a)

-1.9999999999999931

In [57]:
# Eigenvalues and eigenvectors
np.linalg.eig(a)

(array([-0.08663023, 23.08663023]),
 array([[-0.73704409, -0.64344003],
        [ 0.67584466, -0.76549652]]))

In [59]:
# Multiply matrices
np.dot(a, a)

array([[232, 253],
       [276, 301]])