NumPy Array :Ordered collection of elements of basic data types of given length

In [1]:
import numpy as np
lst =[2,3,4,5]
print(type(lst))
x= np.array(lst)
print(type(x))

<class 'list'>
<class 'numpy.ndarray'>


In [2]:
print(x)

[2 3 4 5]


Numpy Array can handle different categorical entities

In [3]:
x=np.array([2,3,'n',5])
print(x)

['2' '3' 'n' '5']


GENERATING NUMPY ARRAYS USING linspace()

In [3]:
b= np.linspace(start = 1, stop = 5, num = 15, retstep = True)
print(b)

(array([1.        , 1.28571429, 1.57142857, 1.85714286, 2.14285714,
       2.42857143, 2.71428571, 3.        , 3.28571429, 3.57142857,
       3.85714286, 4.14285714, 4.42857143, 4.71428571, 5.        ]), 0.2857142857142857)


GENERATING NUMPY ARRAYS USING arange()

In [6]:
d = np.arange(start = 1, stop = 10,step=3)
print(d)

[1 4 7]


GENERATING ONES

In [7]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
GENERATING ONES

In [8]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

RANDOM NUMBER GENERATION :

In [19]:
np.random.rand(10)

array([[0.88506365, 0.77469837, 0.80707042, 0.32880577, 0.3147106 ,
        0.15507787, 0.97740138, 0.66062337, 0.75390217, 0.28953164]])

In [12]:
np.random.rand(5,2)

array([[0.25399494, 0.42920775],
       [0.88728989, 0.79967066],
       [0.46175102, 0.29393343],
       [0.47102252, 0.35231488],
       [0.71691645, 0.05709748]])

NUMPY BENEFITS : TIME COMPLEXITY AND SPACE COMPLEXITY

In [77]:
import timeit
code='''
def getsum():
    x=list(range(10000))
    return sum(x)
print(getsum())
'''
print(timeit.timeit(stmt = code,number = 5))

49995000
49995000
49995000
49995000
49995000
0.005123911953887728


In [78]:
import timeit

code='''
import numpy as np
def getsum():
    x=np.arange(start = 0,stop = 10000)
    return np.sum(x)
print(getsum())
'''
print(timeit.timeit(stmt = code,number = 5))

49995000
49995000
49995000
49995000
49995000
0.0018348021610563592


In [79]:
import sys
x=list(range(1000))
print(sys.getsizeof(1)*len(x))

28000


In [80]:
import sys
import numpy as np
x=np.arange(0,1000)
print(x.itemsize*x.size)

4000


RESHAPING THE NUMPY ARRAY:

In [20]:
grid = np.arange(start = 1,stop = 10).reshape(3,3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


ARRAY DIMENSIONS

In [22]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.shape)
print(a)

(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


NUMPY ADDITION

In [23]:
np.sum(a)

45

In [24]:
np.sum(a,axis=0)

array([12, 15, 18])

In [25]:
np.sum(a,axis = 1)

array([ 6, 15, 24])

In [32]:
b=np.array([[11,12,13],[14,15,16],[17,18,19]])
np.add(a,b)

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [33]:
a.shape

(3, 3)

In [34]:
b.shape

(3, 3)

In [35]:
np.remainder(a,b)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

np.multiply(),np.subtract(),np.divide(),np.remainder()

ACCESSING COMPONENTS OF NUMPY ARRAY(INDEXING)

In [15]:
a[0,1]

2

In [37]:
a[:,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [17]:
a[:,0]

array([1, 4, 7])

In [18]:
a[0,:]

array([1, 2, 3])

In [19]:
a[:2,:2]

array([[1, 2],
       [4, 5]])

In [20]:
np.transpose(a)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [42]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
np.append(a,[[10,11,12]],axis = 0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [43]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [38]:
a = np.insert(a,1,[10,11,12],axis = 1)
print(a)

[[ 1 10  2  3]
 [ 4 11  5  6]
 [ 7 12  8  9]]


In [45]:
np.delete(a,1,axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])