In [3]:
import warnings
import numpy as np
warnings.filterwarnings('ignore')

In [4]:
np.set_printoptions(threshold = 100)

In [6]:
# 0. Numpy version

np.__version__


'1.19.2'

In [7]:
# 1. Create an empty array

empty_array = np.empty([2, 2], int)

print(empty_array)

print(empty_array.shape)

print(empty_array.size)

[[  701945038  1314907155]
 [ 1380416951 -2004713262]]
(2, 2)
4


In [8]:
# 2. Check whether the array is empty

a = np.array([])
b = np.array([1, 2])

def check_empty(a):
    if a.size == 0:
        print(a, ' : Empty')
    else:
        print(b, ' : Non Empty')
        
check_empty(a)
check_empty(b)

[]  : Empty
[1 2]  : Non Empty


In [9]:
# 3. Check elements count

c = np.array([])
d = np.array([1, 2])

def get_elements(c_array):
    return c_array.ndim and c_array.size
        
print(c, ', elements_count : ', get_elements(c))
print(d, ', elements_count : ', get_elements(d))

[] , elements_count :  0
[1 2] , elements_count :  2


In [10]:
# 4. Arrange numpy between numbers

a = np.arange(4, 12)

print(a)
print(a, '.shape : ', a.shape)

[ 4  5  6  7  8  9 10 11]
[ 4  5  6  7  8  9 10 11] .shape :  (8,)


In [11]:
# 5. Arrange numpy between numbers with intervals

c = np.arange(12, 30, 3)

print(c)
print(c, '.shape : ', c.shape)

[12 15 18 21 24 27]
[12 15 18 21 24 27] .shape :  (6,)


In [12]:
# 6. Array reshape

c = np.arange(12, 30, 3)
d = c.reshape(2, 3)

print(c)
print(c, '.shape : ', c.shape)
print('\nAfter reshaping : ')
print(d)
print(d, '.shape : ', d.shape)

[12 15 18 21 24 27]
[12 15 18 21 24 27] .shape :  (6,)

After reshaping : 
[[12 15 18]
 [21 24 27]]
[[12 15 18]
 [21 24 27]] .shape :  (2, 3)


In [13]:
# 7. Create a numpy with random integers

a = np.random.randint(10, size = 5)

print(a)

[9 4 7 9 2]


In [14]:
# 8. Create a numpy with random integers and size

a = np.random.randint(10, size = (2, 3))

print(a)
print(a, '.shape : ', a.shape)
print('datatype : ', a.dtype)

[[5 0 7]
 [5 8 0]]
[[5 0 7]
 [5 8 0]] .shape :  (2, 3)
datatype :  int32


In [15]:
# 9. Array of strings

a = np.array(('Toronto','Montreal','New York'))
print(a)
print(a.dtype)

['Toronto' 'Montreal' 'New York']
<U8


In [16]:
# 10. Numpy array with strings and explicit dtype

x = np.array(['Toronto', 'Montreal'], dtype=str)

print(x)
print(x.dtype)

['Toronto' 'Montreal']
<U8


In [17]:
# 11. Print without truncation

x = np.arange(10000)

print('Before setting print options : ')
print(x) # this will print with the truncation

# set
import sys
# np.set_printoptions(threshold = sys.maxsize)

# print('\nAfter setting print options : ')
# print(a) # this will print everything without truncation

Before setting print options : 
[   0    1    2 ... 9997 9998 9999]


In [19]:
a = np.asarray([ [1,2,3], [4,5,6]])
print(a)
np.savetxt("abc.csv", a, delimiter=",") # this will save the numpy to csv file

[[1 2 3]
 [4 5 6]]


In [20]:
# 13. Get the nth column of an array

x = np.array([[1, 2], [3, 4], [5, 6]])

print('Numpy array:')
print(x)

y = x[:,0]
print('\nx[:,0]:')
print(y)

z = x[:, 1]
print('\nx[:, 1]:')
print(z)

a = x[1,:]
print('\nx[1,:]:')
print(a)

Numpy array:
[[1 2]
 [3 4]
 [5 6]]

x[:,0]:
[1 3 5]

x[:, 1]:
[2 4 6]

x[1,:]:
[3 4]


In [22]:
#  Reshape with -1 (lazy option)

a = np.matrix([[1, 2, 3, 4], [5, 6, 7, 8], [10, 11, 12, 21]])
print('Original Numpy Array:')
print(a)
print('original shape: ', a.shape)

c = np.reshape(a, -1)
print('\nnp.reshape(a, -1):')
print(c)
print('new shape: ', c.shape)

d = np.reshape(a, (1, -1))
print('\nnp.reshape(a, (1, -1)):')
print(d)
print('new shape: ', d.shape)

e = np.reshape(a, (2, -1))
print('\nnp.reshape(a, (2, -1)):')
print(e)
print('new shape: ', e.shape)

f = np.reshape(a, (3, -1))
print('\nnp.reshape(a, (3, -1)):')
print(f)
print('new shape: ', f.shape)

g = np.reshape(a, (4, -1))
print('\nnp.reshape(a, (4, -1)):')
print(g)
print('new shape: ', g.shape)

Original Numpy Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 11 12 21]]
original shape:  (3, 4)

np.reshape(a, -1):
[[ 1  2  3  4  5  6  7  8 10 11 12 21]]
new shape:  (1, 12)

np.reshape(a, (1, -1)):
[[ 1  2  3  4  5  6  7  8 10 11 12 21]]
new shape:  (1, 12)

np.reshape(a, (2, -1)):
[[ 1  2  3  4  5  6]
 [ 7  8 10 11 12 21]]
new shape:  (2, 6)

np.reshape(a, (3, -1)):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 11 12 21]]
new shape:  (3, 4)

np.reshape(a, (4, -1)):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]
 [11 12 21]]
new shape:  (4, 3)


In [23]:
#  Numpy with precision

x = np.random.random(10)

print('Original Array:')
print(x)

print('\nAfter setting presicion:')
np.set_printoptions(precision = 2)
print(x)

# resetting precision to default (8)
np.set_printoptions(precision = 8)

Original Array:
[0.63347121 0.29655315 0.03073352 0.42947041 0.96138896 0.68553294
 0.20799756 0.24593038 0.96198513 0.58234347]

After setting presicion:
[0.63 0.3  0.03 0.43 0.96 0.69 0.21 0.25 0.96 0.58]


In [25]:
#randint
a = np.random.randint(0, 10, (3,3))
print('randint  : ')
print(a)



randint  : 
[[4 7 6]
 [1 6 7]
 [0 6 6]]


In [26]:
#inverse
b = np.array([[2,3],[4,5]])
print('Before Inverse : ')
print(b)

c = np.linalg.inv(b)
print('After Inverse : ')
print(c)

Before Inverse : 
[[2 3]
 [4 5]]
After Inverse : 
[[-2.5  1.5]
 [ 2.  -1. ]]


In [27]:
#Numpy compare

a = np.arange(12).reshape((3, 4))
print(a)

a_bool = a < 6
print(a_bool)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ True  True  True  True]
 [ True  True False False]
 [False False False False]]


In [28]:
# flipup = flip ud = up / down

a = np.arange(4).reshape(2, 2)
print('Before : ')
print(a)

print('\nAfter : ')
b = np.flipud(a)
print(b)

Before : 
[[0 1]
 [2 3]]

After : 
[[2 3]
 [0 1]]


In [29]:
#Flip a numpy array by using fliplr (horizontally)

a = np.arange(10).reshape(2, 5)
print('Before : ')
print(a)

print('\nAfter : ')
b = np.fliplr(a)
print(b)

Before : 
[[0 1 2 3 4]
 [5 6 7 8 9]]

After : 
[[4 3 2 1 0]
 [9 8 7 6 5]]


In [30]:
a = np.arange(10).reshape(2, 5)
print('Before : ')
print(a)

print('\nAfter : ')
b = np.flip(a)
print(b)

Before : 
[[0 1 2 3 4]
 [5 6 7 8 9]]

After : 
[[9 8 7 6 5]
 [4 3 2 1 0]]


In [31]:
 #Convert numpy array to list

a = np.arange(10).reshape(2, 5)
print('Before : ')
print(a)
# print(d.dtype)
print(type(a))
print(type(a[0]))
print(type(a[0][0]))

b = a.tolist()
print('\nAfter : ')
print(b)
print(type(b))
print(type(b[0]))
print(type(b[0][0]))

Before : 
[[0 1 2 3 4]
 [5 6 7 8 9]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.int32'>

After : 
[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]
<class 'list'>
<class 'list'>
<class 'int'>


In [32]:
# numpy where

a = np.arange(8).reshape((2, 4))
print('Before : ')
print(a)

print('\nAfter : ')
b = np.where(a < 4, 0, 20)
print(b)

# Note: it matches, replace with 0, if not replace with 20

Before : 
[[0 1 2 3]
 [4 5 6 7]]

After : 
[[ 0  0  0  0]
 [20 20 20 20]]


In [33]:
#Numpy where with multiple conditions

a = np.arange(8).reshape((2, 4))
print('Before : ')
print(a)

print('\nAfter : ')
b = np.where((a > 3) & (a < 7), 0, 20)
print(b)

Before : 
[[0 1 2 3]
 [4 5 6 7]]

After : 
[[20 20 20 20]
 [ 0  0  0 20]]


In [34]:
#List to numpy array

a = [0, 1, 2]
print('Before : ')
print(a)

print('\nAfter : ')
b = np.array(a)
print(b)
print(b.dtype)

Before : 
[0, 1, 2]

After : 
[0 1 2]
int32


In [35]:
 #List to numpy array with explicit dtype

a = [0, 1, 2]
print('Before : ')
print(a)

print('\nAfter : ')
b = np.array(a, dtype = float)
print(b)
print(b.dtype)

Before : 
[0, 1, 2]

After : 
[0. 1. 2.]
float64


In [36]:
a = np.random.randint(0, 10, 10)
b = np.random.randint(0, 10, 10)
print(a)
print(b)
print('common values between a and b : ', np.intersect1d(a,b))

[9 9 7 2 2 2 3 6 4 8]
[6 5 0 2 2 5 3 9 6 5]
common values between a and b :  [2 3 6 9]


In [37]:
# 41. Get today in numpy and deltas

today = np.datetime64('today', 'D')
print('today          : ', today)

after2days = np.datetime64('today', 'D') + np.timedelta64(2, 'D')
print('after 2 days   : ', after2days)

before3days = np.datetime64('today', 'D') - np.timedelta64(3, 'D')
print('before 3 days  : ', before3days)

after1week = np.datetime64('today', 'D') + np.timedelta64(1, 'W')
print('after 1 week   : ', after1week)

after10weeks = np.datetime64('today', 'D') + np.timedelta64(10, 'W')
print('after 10 weeks : ', after10weeks)

today          :  2021-03-13
after 2 days   :  2021-03-15
before 3 days  :  2021-03-10
after 1 week   :  2021-03-20
after 10 weeks :  2021-05-22


In [38]:
#Between two Dates

a = np.arange('2020-09-15', '2020-09-25', dtype='datetime64[D]')
print('Between two dates : 2020-09-15 and 2020-09-25')
print(a)

a = np.arange('2020-09', '2020-10', dtype='datetime64[D]')
print('\nBetween 2 months : 2020-09 and 2020-10')
print(a)

Between two dates : 2020-09-15 and 2020-09-25
['2020-09-15' '2020-09-16' '2020-09-17' '2020-09-18' '2020-09-19'
 '2020-09-20' '2020-09-21' '2020-09-22' '2020-09-23' '2020-09-24']

Between 2 months : 2020-09 and 2020-10
['2020-09-01' '2020-09-02' '2020-09-03' '2020-09-04' '2020-09-05'
 '2020-09-06' '2020-09-07' '2020-09-08' '2020-09-09' '2020-09-10'
 '2020-09-11' '2020-09-12' '2020-09-13' '2020-09-14' '2020-09-15'
 '2020-09-16' '2020-09-17' '2020-09-18' '2020-09-19' '2020-09-20'
 '2020-09-21' '2020-09-22' '2020-09-23' '2020-09-24' '2020-09-25'
 '2020-09-26' '2020-09-27' '2020-09-28' '2020-09-29' '2020-09-30']


In [40]:
#Random array and sorting

a = np.random.random(5)

print('Before : ')
print(a)

a.sort()
print('\nAfter : ')
print(a)

Before : 
[0.14079638 0.39642563 0.28766697 0.83654587 0.28458214]

After : 
[0.14079638 0.28458214 0.28766697 0.39642563 0.83654587]


In [41]:
a = np.random.randint(50, 100, 5)

print('Before : ')
print(a)

a.sort()
print('\nAfter : ')
print(a)

Before : 
[94 61 72 67 61]

After : 
[61 61 67 72 94]


In [44]:
#Find the nearest element in the array

a = np.arange(10, 60, 7)
print(a)

b = 23
#flat is iterable object
c = a.flat[np.abs(a - b).argmin()]

print(f'Elemenet near by {b} : {c}')

[10 17 24 31 38 45 52 59]
Elemenet near by 23 : 24


In [45]:
#Shuffle

a = np.arange(20)
print('Before : ')
print(a)

np.random.shuffle(a)

print('\nAfter : ')
print(a)

Before : 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

After : 
[12 14  7 10  3  1 16 11  8 19 17  4  6 13  9 18 15  0  5  2]


In [46]:
#Using amin function

x = np.arange(10).reshape((2, 5))
print('x:')
print(x)

print('\nnp.amin(x, 1) : ')
print(np.amin(x, 1))

x:
[[0 1 2 3 4]
 [5 6 7 8 9]]

np.amin(x, 1) : 
[0 5]


In [47]:
x = np.arange(6).reshape((2, 3))
print('x:')
print(x)

print('\nx.min(axis = 0) : ')
print(x.min(axis = 0))

x:
[[0 1 2]
 [3 4 5]]

x.min(axis = 0) : 
[0 1 2]


In [48]:
# column percentile
x = np.arange(6).reshape((2, 3))
print('x:')
print(x)

print('\nnp.percentile(x, 90, 0): ')
print(np.percentile(x, 90, 0))

x:
[[0 1 2]
 [3 4 5]]

np.percentile(x, 90, 0): 
[2.7 3.7 4.7]


In [49]:
# row percentile
x = np.arange(6).reshape((2, 3))
print('x:')
print(x)

print('\nnp.percentile(x, 90, 0): ')
print(np.percentile(x, 90, 1))

x:
[[0 1 2]
 [3 4 5]]

np.percentile(x, 90, 0): 
[1.8 4.8]


In [50]:
 #Find median

x = np.arange(6).reshape((2, 3))
print('x:')
print(x)

print('\nnp.median(x): ')
print(np.median(x))

x:
[[0 1 2]
 [3 4 5]]

np.median(x): 
2.5


In [52]:
#Covariance matrix

x = np.array([0, 1, 2])
y = np.array([7, 8, 9])

print('x:')
print(x)
print('\ny:')
print(y)

print('\nnp.cov(x, y): ')
print(np.cov(x, y))



x:
[0 1 2]

y:
[7 8 9]

np.cov(x, y): 
[[1. 1.]
 [1. 1.]]


In [53]:
x = np.array([1, 2, 2, 1, 1, 1, 5, 5])

print('x:')
print(x)

print('\nnp.bincount(x): ')
print(np.bincount(x))

# how to interpret

#    starts from 0
#    ends with 5
    
#    0 appears 0 times
#    1 appears 4 times

x:
[1 2 2 1 1 1 5 5]

np.bincount(x): 
[0 4 2 0 0 2]


In [54]:
#Shuffle

x = np.arange(10)

print('x Before shuffling:')
print(x)

print('\nx After shuffling:')
np.random.shuffle(x)
print(x)

x Before shuffling:
[0 1 2 3 4 5 6 7 8 9]

x After shuffling:
[3 0 2 9 1 7 8 6 4 5]


In [56]:
#Seed for random
np.random.seed(12)

a = np.random.rand(4)
print('Random array after first seed:')
print(a)

np.random.seed(12)
b = np.random.rand(4)
print('\nRandom array after second seed:')
print(b)

c = np.random.rand(4)
print('\nRandom array after no seed:')
print(c)


Random array after first seed:
[0.15416284 0.7400497  0.26331502 0.53373939]

Random array after second seed:
[0.15416284 0.7400497  0.26331502 0.53373939]

Random array after no seed:
[0.01457496 0.91874701 0.90071485 0.03342143]


In [57]:
#Find the diff

x = np.array([0, 1, 2, 5, 0])
y = np.array([0, 1, 4])

print('x:')
print(x)

print('\ny:')
print(y)

print('\nnp.setdiff1d(x, y):')
print(np.setdiff1d(x, y))

x:
[0 1 2 5 0]

y:
[0 1 4]

np.setdiff1d(x, y):
[2 5]


In [58]:
#Pretty print - suppress the scientific notation

x = np.array([1.2e-10, 2.1, 23])
print('Before:')
print(x)

np.set_printoptions(suppress = True)
print('\nAfter suppressing the scientific notation:')
print(x)

# reset
np.set_printoptions(suppress = False)

Before:
[1.2e-10 2.1e+00 2.3e+01]

After suppressing the scientific notation:
[ 0.   2.1 23. ]


In [59]:
#Convert flot array to int array

x = np.array([[2.0, 8.8], [2.3, 1.9]])
print('Before:')
print(x)

y = x.astype(int)
print('\nAfter changing the datatype:')
print(y)

z = np.int_(x)
print('\nAfter changing the datatype by using int_:')
print(z)

Before:
[[2.  8.8]
 [2.3 1.9]]

After changing the datatype:
[[2 8]
 [2 1]]

After changing the datatype by using int_:
[[2 8]
 [2 1]]


In [60]:
# Compare Numpy datetime

print("np.datetime64('2020') == np.datetime64('2020-01-01'):")
print(np.datetime64('2020') == np.datetime64('2020-01-01'))

print("\nnp.datetime64('2020-01') == np.datetime64('2020-01-02'):")
print(np.datetime64('2020-01') == np.datetime64('2020-01-02'))

np.datetime64('2020') == np.datetime64('2020-01-01'):
True

np.datetime64('2020-01') == np.datetime64('2020-01-02'):
False


In [61]:
#Reverse 1D array

x = np.arange(4)
print('Before:')
print(x)

y = x[::-1]
print('\nAfter reversing:')
print(y)

Before:
[0 1 2 3]

After reversing:
[3 2 1 0]


In [62]:
# 2d arary reverse
x = np.arange(8).reshape(2, -1)
print('Before:')
print(x)

y = x[::-1]
print('\nAfter reversing:')
print(y)

Before:
[[0 1 2 3]
 [4 5 6 7]]

After reversing:
[[4 5 6 7]
 [0 1 2 3]]


In [63]:
#Reverse 2D array with elements

x = np.arange(8).reshape(2, -1)
print('Before:')
print(x)

y = np.flip(x)
print('\nAfter reversing with flip:')
print(y)

y = np.flipud(x)
print('\nAfter reversing with flipud:')
print(y)

y = np.fliplr(x)
print('\nAfter reversing with fliplr:')
print(y)

Before:
[[0 1 2 3]
 [4 5 6 7]]

After reversing with flip:
[[7 6 5 4]
 [3 2 1 0]]

After reversing with flipud:
[[4 5 6 7]
 [0 1 2 3]]

After reversing with fliplr:
[[3 2 1 0]
 [7 6 5 4]]


In [64]:
#Delete specific indices

a = np.array([1, 3, 5, 4, 7])
print('Before:')
print(a)

indices = [2, 3]
b = np.delete(a, indices)

print('\nAfter Deleting specific indices:')
print(b)

Before:
[1 3 5 4 7]

After Deleting specific indices:
[1 3 7]


In [65]:
#Deleting specific elements

a = np.array([1, 4, 5, 4])
print('Before:')
print(a)

b = np.array([3, 4])
c = np.setdiff1d(a, b)

print('\nAfter Deleting specific elements:')
print(c)

Before:
[1 4 5 4]

After Deleting specific elements:
[1 5]


In [67]:
a = np.empty((3, 2,))
a[:] = np.nan
print('nan using empty:')
print(a)


nan using empty:
[[nan nan]
 [nan nan]
 [nan nan]]


In [68]:
#Replace values with specific condition

import numpy as np
a = np.random.rand(2, 4)
print('Before:')
print(a)

a[a > 0.5] = 0.5
print('\nAfter updating a[a > 0.5] = 0.5:')
print(a)

Before:
[[0.95694934 0.13720932 0.28382835 0.60608318]
 [0.94422514 0.85273554 0.00225923 0.52122603]]

After updating a[a > 0.5] = 0.5:
[[0.5        0.13720932 0.28382835 0.5       ]
 [0.5        0.5        0.00225923 0.5       ]]


In [69]:
#Numpy Roll

import numpy as np

x = np.arange(1, 7).reshape(2, 3)

print(x)

y = np.roll(x, 1, axis = 1)

print('\nAfter:')
print(y)

[[1 2 3]
 [4 5 6]]

After:
[[3 1 2]
 [6 4 5]]


In [70]:
#Numpy Roll

import numpy as np

x = np.arange(1, 7).reshape(2, 3)

print(x)

y = np.roll(x, 1, axis = 0)

print('\nAfter:')
print(y)

[[1 2 3]
 [4 5 6]]

After:
[[4 5 6]
 [1 2 3]]


In [73]:
#Roll elements

x = np.arange(10)
y = np.roll(x, 3)

print(x)

print(y)

[0 1 2 3 4 5 6 7 8 9]
[7 8 9 0 1 2 3 4 5 6]


In [74]:
#Rearrange array with specified index

a = np.array([11, 22, 33, 44, 55])
print('Before:')
print(a)

idx = [4, 2, 0, 1, 3]

b = a[idx]

print('\nAfter:')
print(b)

Before:
[11 22 33 44 55]

After:
[55 33 11 22 44]


In [75]:
#Serialize array with pickle

a = np.array([10, 20])
print('Before:')
print(a)

import pickle

b = pickle.dumps(a, protocol = 4)

print('\nSerialized Numpy Array:')
print(b)

c = pickle.loads(b)

print('\nDe-serialized Numpy Array:')
print(c)


Before:
[10 20]

Serialized Numpy Array:
b'\x80\x04\x95\x90\x00\x00\x00\x00\x00\x00\x00\x8c\x15numpy.core.multiarray\x94\x8c\x0c_reconstruct\x94\x93\x94\x8c\x05numpy\x94\x8c\x07ndarray\x94\x93\x94K\x00\x85\x94C\x01b\x94\x87\x94R\x94(K\x01K\x02\x85\x94h\x03\x8c\x05dtype\x94\x93\x94\x8c\x02i4\x94\x89\x88\x87\x94R\x94(K\x03\x8c\x01<\x94NNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00t\x94b\x89C\x08\n\x00\x00\x00\x14\x00\x00\x00\x94t\x94b.'

De-serialized Numpy Array:
[10 20]


In [76]:
#Transpose

a = np.arange(6).reshape(2, -1) 

print('Before:')
print(a)

b = np.transpose(a)
print('\nAfter:')
print(b)

Before:
[[0 1 2]
 [3 4 5]]

After:
[[0 3]
 [1 4]
 [2 5]]


In [77]:
#Float anomalies in Numpy Arange

for i in np.arange(0.0, 2.1, 0.1):
    print(i)

0.0
0.1
0.2
0.30000000000000004
0.4
0.5
0.6000000000000001
0.7000000000000001
0.8
0.9
1.0
1.1
1.2000000000000002
1.3
1.4000000000000001
1.5
1.6
1.7000000000000002
1.8
1.9000000000000001
2.0


In [78]:
#Resize a list with rounds

a_list = [10, 20, 30]
result = np.resize(a_list, 12)

print(result)

[10 20 30 10 20 30 10 20 30 10 20 30]


In [80]:
# Business Day Count

a = np.busday_count('2020-01', '2021-01')

print(a)

print('What not possible with array :) :-)')

262
What not possible with array :) :-)
