In [1]:
list1=[1,2,3]
list1

[1, 2, 3]

In [ ]:
#pip install numpy

In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

In [3]:
type(np)

module

In [5]:
arr=np.array([1,2,3,3,4,4,5,7,10.0])
arr

array([ 1.,  2.,  3.,  3.,  4.,  4.,  5.,  7., 10.])

In [6]:
type(arr)

numpy.ndarray

In [7]:
list1={1:1,2:5,8:2}
list1

{1: 1, 2: 5, 8: 2}

In [8]:
h=np.array(list1)
h

array({1: 1, 2: 5, 8: 2}, dtype=object)

In [9]:
# attributes numpy array
shape-gets the shape of an array
size-no of elements present array
ndim=dimension of an array
dtype=type of elements present the array
itemsize-memory aquried elements of array

SyntaxError: invalid syntax (603412036.py, line 2)

In [10]:
arr.shape

(9,)

In [11]:
arr.size

9

In [12]:
arr.ndim

1

In [13]:
arr.dtype

dtype('float64')

In [14]:
arr.itemsize

8

In [15]:
arr2=np.array([[1,2,3,6],[4,5,6,9]])
arr2

array([[1, 2, 3, 6],
       [4, 5, 6, 9]])

In [17]:
arr2.shape

(2, 4)

In [18]:
arr2.size

8

In [33]:
arr2.ndim

2

In [19]:
arr2.dtype

dtype('int32')

In [20]:
arr2.itemsize

4

In [22]:
arr3=np.array([[[1,2],[6,7]],[[5,6],[7,8]],[[12,13],[14,15]]])
arr3

array([[[ 1,  2],
        [ 6,  7]],

       [[ 5,  6],
        [ 7,  8]],

       [[12, 13],
        [14, 15]]])

In [24]:
arr3.shape

(3, 2, 2)

In [42]:
arr3.size

12

In [43]:
arr3.dtype

dtype('int32')

In [44]:
arr3.ndim

3

In [45]:
arr3.itemsize

4

In [25]:
d=np.array(16)
d

array(16)

In [52]:
d1=np.array([16])
d1

array([16])

In [48]:
d.ndim,d1.ndim

(0, 1)

In [53]:
d.shape,d1.shape

((), (1,))

In [54]:
d.size,d1.size

(1, 1)

In [55]:
d.dtype,d1.dtype

(dtype('int32'), dtype('int32'))

In [56]:
d.itemsize,d1.itemsize

(4, 4)

In [59]:
arr5=np.array([[["qasdfg","asdfb","c"],["t","gasdf","h"]],[["d","h","j"],["u","y","h"]]])
arr5

array([[['qasdfg', 'asdfb', 'c'],
        ['t', 'gasdf', 'h']],

       [['d', 'h', 'j'],
        ['u', 'y', 'h']]], dtype='<U6')

In [60]:
arr5.shape,arr5.size,arr5.ndim,arr5.dtype,arr5.itemsize

((2, 2, 3), 12, 3, dtype('<U6'), 24)

In [61]:
type(arr5)

numpy.ndarray

In [66]:
a=np.array([[[12,78],[5,8]],[[1,2],[4,5]]],ndmin=5)
a

array([[[[[12, 78],
          [ 5,  8]],

         [[ 1,  2],
          [ 4,  5]]]]])

In [26]:
list2=((1,2,3),(4,5,6),(7,8,9))
list2

((1, 2, 3), (4, 5, 6), (7, 8, 9))

In [27]:
f=np.array(list2)
f

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
arr

array([ 1.,  2.,  3.,  3.,  4.,  4.,  5.,  7., 10.])

In [29]:
list7=list(arr)
list7

[1.0, 2.0, 3.0, 3.0, 4.0, 4.0, 5.0, 7.0, 10.0]

In [77]:
type(list7)

list

In [80]:
tup=tuple(f)

In [81]:
tup

(array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]))

In [82]:
arr

array([ 1.,  2.,  3.,  3.,  4.,  4.,  5.,  7., 10.])

In [83]:
s=set(arr)

In [84]:
s

{1.0, 2.0, 3.0, 4.0, 5.0, 7.0, 10.0}

In [86]:
dict1=dict(f)
dict1

ValueError: dictionary update sequence element #0 has length 3; 2 is required

In [ ]:
#built in function
zeros=will generate array of zeros

In [87]:
a=np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [90]:
a=np.zeros((2,2,3),dtype=int)
a

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [94]:
np.zeros(shape=[3,4,2])

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
#ones = generating an array of ones

In [30]:
a=np.ones((4,),dtype=int)
a

array([1, 1, 1, 1])

In [ ]:
# empty 

In [31]:
np.empty((2,4))

array([[4.67296746e-307, 1.69121096e-306, 3.11522054e-307,
        1.42413555e-306],
       [1.78019082e-306, 1.37959740e-306, 6.23057349e-307,
        1.42419530e-306]])

In [32]:
np.full((2,2),[True,False])

array([[ True, False],
       [ True, False]])

In [ ]:
#arange
returns evenly spaced values within a given a range
arange(start,stop(ex),step)


In [33]:
a=np.arange(1,21,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
#linspace
returns evenly spaced numbers within the given range
linspace(start,stop,number)

In [36]:
a=np.linspace(1,201,3)
a

array([  1., 101., 201.])

In [37]:
b=np.arange(0,10.5,5)
b

array([ 0.,  5., 10.])

In [120]:
b=np.linspace(0,10.5,5)
b

array([ 0.   ,  2.625,  5.25 ,  7.875, 10.5  ])

In [121]:
c=np.arange(0,100,11)
c

array([ 0, 11, 22, 33, 44, 55, 66, 77, 88, 99])

In [10]:
c=np.linspace(0,100,25)
c

array([  0.        ,   4.16666667,   8.33333333,  12.5       ,
        16.66666667,  20.83333333,  25.        ,  29.16666667,
        33.33333333,  37.5       ,  41.66666667,  45.83333333,
        50.        ,  54.16666667,  58.33333333,  62.5       ,
        66.66666667,  70.83333333,  75.        ,  79.16666667,
        83.33333333,  87.5       ,  91.66666667,  95.83333333,
       100.        ])

In [38]:
e=np.arange(10,20,3)
e

array([10, 13, 16, 19])

In [124]:
e=np.linspace(10,20,3)
e

array([10., 15., 20.])

In [13]:
a=np.random.rand(10)
a

array([0.20540163, 0.09107654, 0.39097975, 0.06946185, 0.4823832 ,
       0.28085372, 0.6256082 , 0.88422331, 0.29856493, 0.90619334])

In [137]:
#array([0.51157562, 0.17881898, 0.92487571, 0.5854005 ,0.9207735 ,0.6085032 , 0.07108224, 0.98883636, 0.89867808, 0.97084618])

In [39]:
a

array([  1., 101., 201.])

In [86]:
x=np.random.rand(2,2,3)

In [89]:
x

array([[[0.13521817, 0.32414101, 0.14967487],
        [0.22232139, 0.38648898, 0.90259848]],

       [[0.44994999, 0.61306346, 0.90234858],
        [0.09928035, 0.96980907, 0.65314004]]])

In [91]:
x[0,0,0]

0.13521817340545206

In [19]:
import random

In [32]:
#random.seed(5)
random.random()

0.922324996665417

In [28]:
0.4745706786885481

0.4745706786885481

In [33]:
np.random.seed(0)
np.random.rand(2,2,3)

array([[[0.5488135 , 0.71518937, 0.60276338],
        [0.54488318, 0.4236548 , 0.64589411]],

       [[0.43758721, 0.891773  , 0.96366276],
        [0.38344152, 0.79172504, 0.52889492]]])

In [198]:
low(included),high(exculded)

NameError: name 'low' is not defined

In [37]:
np.random.randint(1,43,5)

array([30, 20, 20, 15, 40])

In [38]:
np.random.randint(10,size=6)

array([0, 1, 9, 9, 0, 4])

In [39]:
np.random.randint(1,400,size=(2,3))

array([[152, 164, 371],
       [184,  29, 291]])

In [42]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [43]:
np.identity(6,dtype=int)

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

In [ ]:
#slicing and dicing in an array

In [49]:
a=np.arange(20).reshape(2,10)

In [50]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [2]:
import numpy as np
arr=np.linspace(10,200,11)
arr

array([ 10.,  29.,  48.,  67.,  86., 105., 124., 143., 162., 181., 200.])

In [3]:
arr[4]

86.0

In [57]:
arr[-7:-4]

array([ 86., 105., 124.])

In [ ]:
-7 , -6 ,-5


In [ ]:
2:5 -> 2,3,4 stops

In [4]:
arr[-7:2:1]


array([], dtype=float64)

In [222]:
arr[-4:-7:-1]

array([143., 124., 105.])

In [5]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

indexinging[row][column]or[row,column]

In [6]:
arr2[0][1]

2

slicing=[startr:stopr,startc:stopc]

In [7]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr2[1:2,:3]

array([[4, 5, 6]])

In [84]:
arr2[1:,0:2]

array([[4, 5],
       [7, 8]])

In [234]:
arr2[0:2,1:]

array([[2, 3],
       [5, 6]])

In [10]:
arr_2d=np.array([[78,97,24],[25,1,3],[9,4,2]])
arr_2d

array([[78, 97, 24],
       [25,  1,  3],
       [ 9,  4,  2]])

In [11]:
arr_2d[2:,1:3]

array([[4, 2]])

In [237]:
arr_2d[1:,1:2]

array([[1],
       [4]])

In [240]:
arr_2d[:2,2:]

array([[24],
       [ 3]])

In [241]:
arr_2d[:2,1:3]

array([[97, 24],
       [ 1,  3]])

In [242]:
arr_2d

array([[78, 97, 24],
       [25,  1,  3],
       [ 9,  4,  2]])

In [244]:
arr_2d[0:2,0:1]

array([[78],
       [25]])

In [245]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [246]:
a[2,2]

12

In [247]:
a[2:,1:4]

array([[11, 12, 13],
       [16, 17, 18]])

In [250]:
a[:,-3:-2]

array([[ 2],
       [ 7],
       [12],
       [17]])

In [251]:
a[:,2:3]

array([[ 2],
       [ 7],
       [12],
       [17]])

In [252]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [254]:
a[:2,2:3]

array([[2],
       [7]])

In [257]:
a[:3,1:2]

array([[ 1],
       [ 6],
       [11]])

In [258]:
a[1:3,1:3]

array([[ 6,  7],
       [11, 12]])

In [259]:
arrr=np.array([["a","b","c","d"],["b","c","e","g"],["t","i","j","k"],["u","j","o","k"]])

In [260]:
arrr

array([['a', 'b', 'c', 'd'],
       ['b', 'c', 'e', 'g'],
       ['t', 'i', 'j', 'k'],
       ['u', 'j', 'o', 'k']], dtype='<U1')

In [261]:
arrr[1:4,1:3]

array([['c', 'e'],
       ['i', 'j'],
       ['j', 'o']], dtype='<U1')

In [262]:
arrr[1:3,0:2]

array([['b', 'c'],
       ['t', 'i']], dtype='<U1')

In [263]:
arrr[0:2,2:]

array([['c', 'd'],
       ['e', 'g']], dtype='<U1')

In [264]:
arrr[2:4,1:]

array([['i', 'j', 'k'],
       ['j', 'o', 'k']], dtype='<U1')

In [265]:
arr_3d=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
indexing[set][rows][columns]

In [266]:
arr_3d[1][0][1]

6

In [267]:
arr_3d[0,0,0]

1

In [268]:
arr_3d[0,1,1]

4

In [269]:
arr_3d[1,1,1]

8

In [270]:
arr_3d[1,1,0]

7

In [271]:
arr_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
slicing[ss:sts,sr:str,sc:stc]

In [272]:
arr_3d[0:2,0:1,0:]

array([[[1, 2]],

       [[5, 6]]])

In [273]:
arr_3d[0:2,1:,0:]

array([[[3, 4]],

       [[7, 8]]])

In [274]:
arr_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [276]:
arr_3d[0:1,:,:]

array([[[1, 2],
        [3, 4]]])

In [277]:
arr3d=np.arange(30).reshape(3,2,5)
arr3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [278]:
arr3d[0:,1:,1:2]

array([[[ 6]],

       [[16]],

       [[26]]])

In [279]:
arr3d[0:,0:1,2:4]

array([[[ 2,  3]],

       [[12, 13]],

       [[22, 23]]])

In [ ]:
#Arithematic operation

In [95]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [93]:
a*10

array([[  0,  10,  20,  30,  40,  50,  60,  70,  80,  90],
       [100, 110, 120, 130, 140, 150, 160, 170, 180, 190]])

In [94]:
a+a

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38]])

In [96]:
a=np.array([1,2,3,9])
b=np.array([1,2,3,4])

In [98]:
a%b

array([0, 0, 0, 1])

In [99]:
a is b

False

In [100]:
x=a

In [101]:
a is x

True

In [298]:
9 in a

True

In [103]:
10 in a

False

In [104]:
a,b

(array([1, 2, 3, 9]), array([1, 2, 3, 4]))

In [105]:
a<b

array([False, False, False, False])

In [303]:
a

array([1, 2, 3, 9])

In [106]:
a=np.arange(20).reshape(4,5)

In [107]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [307]:
a[a>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [108]:
a[a%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [109]:
a[a%5==0]

array([ 0,  5, 10, 15])

In [110]:
a1=np.array([1,2,3,9])
b1=np.array([1,2,3,4])

In [111]:
a1&b1

array([1, 2, 3, 0])

In [312]:
bin(9)

'0b1001'

In [313]:
bin(4)

'0b100'

In [112]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [113]:
np.multiply(a,a)

array([[ 1,  4],
       [ 9, 16]])

In [115]:
np.matmul(a,a)

array([[ 7, 10],
       [15, 22]])

In [116]:
a1

array([1, 2, 3, 9])

In [117]:
np.cos(a1)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.91113026])

In [118]:
np.sin(a1)

array([0.84147098, 0.90929743, 0.14112001, 0.41211849])

In [119]:
np.tan(a1)

array([ 1.55740772, -2.18503986, -0.14254654, -0.45231566])

In [120]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229, 2.19722458])

In [121]:
np.sqrt(a1)

array([1.        , 1.41421356, 1.73205081, 3.        ])

In [122]:
#truncate ,fix

In [123]:
a=np.trunc([3.667,6.9,9.8])
a

array([3., 6., 9.])

In [124]:
a=np.fix([3.667,6.9,9.8])
a

array([3., 6., 9.])

In [12]:
round(3.4)

3

In [131]:
a=np.around(3.6567345345,3)
a

3.657

In [132]:
round(3.765,2)

3.77

In [ ]:
#floor and ceil

In [332]:
np.floor([3.678,-1.89,7.89,-3.7,4.5,-4.1])

array([ 3., -2.,  7., -4.,  4., -5.])

In [333]:
np.ceil([3.678,-1.89,7.89,-3.7,4.5,-4.1])

array([ 4., -1.,  8., -3.,  5., -4.])

In [133]:
a=4
b=3
np.lcm(a,b)

12

In [336]:
a=10
b=20
np.gcd(a,b)

10

In [134]:
a=np.array([1,2,3,1,2,3,1,4,5,6,4])
np.unique(a)

array([1, 2, 3, 4, 5, 6])

In [135]:
a=np.array([1,2,3,4,5])
b=np.array([1,3,4,5,6])

In [136]:
np.intersect1d(a,b)

array([1, 3, 4, 5])

In [137]:
np.union1d(a,b)

array([1, 2, 3, 4, 5, 6])

In [138]:
np.setdiff1d(b,a)

array([6])

In [139]:
a

array([1, 2, 3, 4, 5])

In [140]:
b

array([1, 3, 4, 5, 6])

In [344]:
a1=np.array([1,3,4,1,7,89,3,5,6])
a1

array([ 1,  3,  4,  1,  7, 89,  3,  5,  6])

In [141]:
a1.max()

9

In [145]:
max(a1)

9

In [146]:
a1

array([1, 2, 3, 9])

In [147]:
a1.argmax()

3

In [148]:
a1.min()

1

In [149]:
a1.argmin()

0

In [350]:
a=np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [351]:
np.trace(a)

30

In [352]:
arr1=np.array([4,3,5,7])
arr1

array([4, 3, 5, 7])

In [353]:
arr1.sum()

19

In [358]:
arr1.mean()

4.75

In [359]:
np.average(arr1)

4.75

In [360]:
np.median(arr1)

4.5

In [366]:
ass=np.sort(arr1)
ass

array([3, 4, 5, 7])

In [365]:
np.median(ass)

4.5

In [367]:
a3=np.array([7,13,15,9,11])
a3

array([ 7, 13, 15,  9, 11])

In [368]:
np.median(a3)

11.0

In [369]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [370]:
np.median(a)

3.0

In [371]:
a.mean()

3.0

In [373]:
np.std(a)

1.4142135623730951

In [374]:
np.std(a,ddof=1)

1.5811388300841898

In [376]:
np.var(a)

2.0

In [372]:
np.sqrt(2)

1.4142135623730951

In [ ]:
#linear algebra(linalg)

In [377]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [378]:
np.linalg.matrix_rank(a)

2

In [379]:
a1=np.array([[1,2,3],[2,1,4],[3,0,5]])
a1

array([[1, 2, 3],
       [2, 1, 4],
       [3, 0, 5]])

In [380]:
np.linalg.matrix_rank(a1)

2

In [381]:
b=np.array([[1,2,3],[2,3,4],[3,5,7]])
b

array([[1, 2, 3],
       [2, 3, 4],
       [3, 5, 7]])

In [382]:
np.linalg.matrix_rank(b)

2

In [383]:
d=np.array([[4,7],[2,6]])
d

array([[4, 7],
       [2, 6]])

In [384]:
np.linalg.det(d)

10.000000000000002

In [385]:
d=np.array([[1,2],[3,4]])
d

array([[1, 2],
       [3, 4]])

In [386]:
np.linalg.det(d)

-2.0000000000000004

In [387]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [388]:
np.linalg.det(a)

-9.51619735392994e-16

In [391]:
s=np.array([[2,1],[7,4]])
s

array([[2, 1],
       [7, 4]])

In [392]:
np.linalg.det(s)

0.9999999999999996

In [393]:
np.linalg.inv(s)

array([[ 4., -1.],
       [-7.,  2.]])

In [394]:
d=np.array([[1,2],[3,4]])
d

array([[1, 2],
       [3, 4]])

In [395]:
np.linalg.inv(d)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [396]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [397]:
np.linalg.inv(a)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [398]:
d=np.array([[1,2],[3,4]])
d

array([[1, 2],
       [3, 4]])

In [400]:
a=np.array([[3,4],[6,7]])

In [401]:
np.matmul(d,a,d)

array([[ 81,  98],
       [177, 214]])

In [402]:
d

array([[ 81,  98],
       [177, 214]])

In [405]:
a

array([[3, 4],
       [6, 7]])

In [415]:
np.linalg.matrix_power(a,1)

array([[3, 4],
       [6, 7]])

In [417]:
4/3

1.3333333333333333

In [ ]:
-3x+4y=5
2x-y=-10

In [13]:
a7=np.array([[-3,4],[2,-1]])
a7
b=np.array([5,-10])
b

array([  5, -10])

In [14]:
np.linalg.det(a7)

-5.000000000000001

In [15]:
np.linalg.inv(a7)

array([[0.2, 0.8],
       [0.4, 0.6]])

In [428]:
np.linalg.solve(a7,b)

array([-7., -4.])

In [429]:
-1+8

7

In [430]:
a7

array([[-3,  4],
       [ 2, -1]])

# 07/10/2024

In [ ]:
x-y=12
2x+y=22

In [431]:
a=np.array([[1,-1],[2,1]])
a

array([[ 1, -1],
       [ 2,  1]])

In [433]:
np.linalg.det(a)

2.9999999999999996

In [434]:
np.linalg.solve(a,b)

array([11.33333333, -0.66666667])

In [432]:
b=np.array([12,22])
b

array([12, 22])

In [437]:
x=np.array([[2,-1],[-1,2]])
x

array([[ 2, -1],
       [-1,  2]])

In [440]:
np.linalg.eig(x)

(array([3., 1.]),
 array([[ 0.70710678,  0.70710678],
        [-0.70710678,  0.70710678]]))

In [ ]:
# copy view:


In [441]:
arr1=np.array([1,2,3,4,5,6])
arr1

array([1, 2, 3, 4, 5, 6])

In [442]:
ar2=arr1.copy()
ar2

array([1, 2, 3, 4, 5, 6])

In [443]:
ar3=arr1.view()
ar3

array([1, 2, 3, 4, 5, 6])

In [444]:
arr1[0]=1000

In [445]:
ar2

array([1, 2, 3, 4, 5, 6])

In [446]:
ar3

array([1000,    2,    3,    4,    5,    6])

In [447]:
ar3[4]=90

In [448]:
arr1


array([1000,    2,    3,    4,   90,    6])

In [449]:
ar2

array([1, 2, 3, 4, 5, 6])

In [451]:
id(arr1),id(ar2),id(ar3)

(1674273341488, 1674273110704, 1674272456496)

In [452]:
arr1

array([1000,    2,    3,    4,   90,    6])

In [453]:
arr4=arr1

In [454]:
arr4

array([1000,    2,    3,    4,   90,    6])

In [455]:
id(arr4)

1674273341488

In [16]:
a=np.arange(1,17)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [17]:
a.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [20]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [23]:
a.resize(1,16)

In [24]:
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]])

In [31]:
v=np.arange(30)
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [32]:
copy1=v.reshape(5,6)
copy1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [33]:
v.reshape(15,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

In [34]:
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [35]:
copy2=v.resize(6,5)
copy2

In [36]:
copy2

In [37]:
v

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [38]:
g=np.arange(40).reshape(2,4,5)
g

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]]])

In [39]:
v

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [40]:
#flatten and ravel

In [41]:
fc=v.flatten()
fc

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [474]:
rv=v.ravel()
rv

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [475]:
v

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [476]:
v[0,1]=200

In [477]:
v

array([[  0, 200,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29]])

In [478]:
fc

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [479]:
rv

array([  0, 200,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29])

In [481]:
g.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [482]:
g.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [483]:
g

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]]])

In [484]:
# iterating an array

In [1]:
import numpy as np
a=np.arange(1,17)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [2]:
for i in a:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


In [3]:
v

NameError: name 'v' is not defined

In [489]:
for i in v:
    print(i)
    for j in i:
        print(j)

[  0 200   2   3   4]
0
200
2
3
4
[5 6 7 8 9]
5
6
7
8
9
[10 11 12 13 14]
10
11
12
13
14
[15 16 17 18 19]
15
16
17
18
19
[20 21 22 23 24]
20
21
22
23
24
[25 26 27 28 29]
25
26
27
28
29


In [490]:
g

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]]])

In [492]:
for i in g:
    print(i)
    for j in i:
        print(j)
        for k in j:
            print(k)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[0 1 2 3 4]
0
1
2
3
4
[5 6 7 8 9]
5
6
7
8
9
[10 11 12 13 14]
10
11
12
13
14
[15 16 17 18 19]
15
16
17
18
19
[[20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]
[20 21 22 23 24]
20
21
22
23
24
[25 26 27 28 29]
25
26
27
28
29
[30 31 32 33 34]
30
31
32
33
34
[35 36 37 38 39]
35
36
37
38
39


In [ ]:
#nditer

In [4]:
for i in np.nditer(a):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


In [5]:
for i in np.ndenumerate(a):
    print(i)

((0,), 1)
((1,), 2)
((2,), 3)
((3,), 4)
((4,), 5)
((5,), 6)
((6,), 7)
((7,), 8)
((8,), 9)
((9,), 10)
((10,), 11)
((11,), 12)
((12,), 13)
((13,), 14)
((14,), 15)
((15,), 16)


In [497]:
v

array([[  0, 200,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29]])

In [498]:
for i in np.ndenumerate(v):
    print(i)

((0, 0), 0)
((0, 1), 200)
((0, 2), 2)
((0, 3), 3)
((0, 4), 4)
((1, 0), 5)
((1, 1), 6)
((1, 2), 7)
((1, 3), 8)
((1, 4), 9)
((2, 0), 10)
((2, 1), 11)
((2, 2), 12)
((2, 3), 13)
((2, 4), 14)
((3, 0), 15)
((3, 1), 16)
((3, 2), 17)
((3, 3), 18)
((3, 4), 19)
((4, 0), 20)
((4, 1), 21)
((4, 2), 22)
((4, 3), 23)
((4, 4), 24)
((5, 0), 25)
((5, 1), 26)
((5, 2), 27)
((5, 3), 28)
((5, 4), 29)


In [501]:
g

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]]])

In [502]:
for i in np.ndenumerate(g):
    print(i)

((0, 0, 0), 0)
((0, 0, 1), 1)
((0, 0, 2), 2)
((0, 0, 3), 3)
((0, 0, 4), 4)
((0, 1, 0), 5)
((0, 1, 1), 6)
((0, 1, 2), 7)
((0, 1, 3), 8)
((0, 1, 4), 9)
((0, 2, 0), 10)
((0, 2, 1), 11)
((0, 2, 2), 12)
((0, 2, 3), 13)
((0, 2, 4), 14)
((0, 3, 0), 15)
((0, 3, 1), 16)
((0, 3, 2), 17)
((0, 3, 3), 18)
((0, 3, 4), 19)
((1, 0, 0), 20)
((1, 0, 1), 21)
((1, 0, 2), 22)
((1, 0, 3), 23)
((1, 0, 4), 24)
((1, 1, 0), 25)
((1, 1, 1), 26)
((1, 1, 2), 27)
((1, 1, 3), 28)
((1, 1, 4), 29)
((1, 2, 0), 30)
((1, 2, 1), 31)
((1, 2, 2), 32)
((1, 2, 3), 33)
((1, 2, 4), 34)
((1, 3, 0), 35)
((1, 3, 1), 36)
((1, 3, 2), 37)
((1, 3, 3), 38)
((1, 3, 4), 39)


In [503]:
v

array([[  0, 200,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29]])

In [504]:
v.transpose()

array([[  0,   5,  10,  15,  20,  25],
       [200,   6,  11,  16,  21,  26],
       [  2,   7,  12,  17,  22,  27],
       [  3,   8,  13,  18,  23,  28],
       [  4,   9,  14,  19,  24,  29]])

In [505]:
v.T

array([[  0,   5,  10,  15,  20,  25],
       [200,   6,  11,  16,  21,  26],
       [  2,   7,  12,  17,  22,  27],
       [  3,   8,  13,  18,  23,  28],
       [  4,   9,  14,  19,  24,  29]])

In [510]:
g

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]]])

In [509]:
g.transpose()

array([[[ 0, 20],
        [ 5, 25],
        [10, 30],
        [15, 35]],

       [[ 1, 21],
        [ 6, 26],
        [11, 31],
        [16, 36]],

       [[ 2, 22],
        [ 7, 27],
        [12, 32],
        [17, 37]],

       [[ 3, 23],
        [ 8, 28],
        [13, 33],
        [18, 38]],

       [[ 4, 24],
        [ 9, 29],
        [14, 34],
        [19, 39]]])

In [6]:
h=np.arange(30).reshape(3,2,5)
h

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [7]:
h.T

array([[[ 0, 10, 20],
        [ 5, 15, 25]],

       [[ 1, 11, 21],
        [ 6, 16, 26]],

       [[ 2, 12, 22],
        [ 7, 17, 27]],

       [[ 3, 13, 23],
        [ 8, 18, 28]],

       [[ 4, 14, 24],
        [ 9, 19, 29]]])

In [513]:
g

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]]])

In [522]:
g.astype('float')

array([[[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]],

       [[20., 21., 22., 23., 24.],
        [25., 26., 27., 28., 29.],
        [30., 31., 32., 33., 34.],
        [35., 36., 37., 38., 39.]]])

In [ ]:
#concatenation

In [523]:
arr=np.array([1,2,3])
arr1=np.array([4,5,6])

In [526]:
arr+arr1

array([5, 7, 9])

In [525]:
np.concatenate((arr,arr1))

array([1, 2, 3, 4, 5, 6])

In [9]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

In [12]:
np.concatenate((array1,array2),axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [13]:
np.concatenate((array1,array2),axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [42]:
g=np.array([[1,2],[3,4],[5,6],[7,8]])
g

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [533]:
np.concatenate((g,g),axis=1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4],
       [5, 6, 5, 6],
       [7, 8, 7, 8]])

In [534]:
array1 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
array2 = np.array([[[9, 10], [11, 12]], [[13, 14], [15, 16]]])

In [536]:
np.concatenate((array1,array2),axis=0)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]]])

In [15]:
np.concatenate((array1,array2),axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [538]:
np.concatenate((array1,array2),axis=2)

array([[[ 1,  2,  9, 10],
        [ 3,  4, 11, 12]],

       [[ 5,  6, 13, 14],
        [ 7,  8, 15, 16]]])

In [539]:
array1 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
array2 = np.array([[[9, 10], [11, 12],[23,24]], [[13, 14], [15, 16],[17,18]]])

In [540]:
np.concatenate((array1,array2))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

In [541]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

In [543]:
np.concatenate((array1,array2))

array([1, 2, 3, 4, 5, 6])

In [16]:
array1

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
array2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [18]:
np.stack((array1,array2))

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [19]:
g=np.array([[1,2],[3,4],[5,6],[7,8]])
j=np.array([[5,6],[7,8],[9,10],[11,12]])

In [20]:
np.concatenate((g,j),axis=1)

array([[ 1,  2,  5,  6],
       [ 3,  4,  7,  8],
       [ 5,  6,  9, 10],
       [ 7,  8, 11, 12]])

In [21]:
np.stack((g,j),axis=1)

array([[[ 1,  2],
        [ 5,  6]],

       [[ 3,  4],
        [ 7,  8]],

       [[ 5,  6],
        [ 9, 10]],

       [[ 7,  8],
        [11, 12]]])

In [551]:
array1 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
array2 = np.array([[[9, 10], [11, 12]], [[13, 14], [15, 16]]])

In [552]:
np.stack((array1,array2))

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [553]:
np.stack((array1,array2),axis=1)

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 9, 10],
         [11, 12]]],


       [[[ 5,  6],
         [ 7,  8]],

        [[13, 14],
         [15, 16]]]])

In [554]:
np.stack((array1,array2),axis=2)

array([[[[ 1,  2],
         [ 9, 10]],

        [[ 3,  4],
         [11, 12]]],


       [[[ 5,  6],
         [13, 14]],

        [[ 7,  8],
         [15, 16]]]])

# 08/10/2024

In [ ]:
# ----1d---
hstack concatenates 1D arrays along the only axis available (axis 0).
vstack with 1D arrays first converts them into 2D row vectors and then stacks them vertically (along axis 0).
hstack: For 1D arrays, it concatenates them into a single 1D array.
dstack: For 1D arrays, it stacks them as rows of a 2D array.


In [22]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

In [23]:
np.stack((array1,array2))

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
np.hstack((array1,array2))

array([1, 2, 3, 4, 5, 6])

In [25]:
np.vstack((array1,array2))

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
np.dstack((array1,array2))

array([[[1, 4],
        [2, 5],
        [3, 6]]])

In [ ]:
---2d---
hstack stacks arrays horizontally (column-wise). It concatenates arrays along the second axis (axis=1).
vstack stacks arrays vertically (row-wise). It concatenates arrays along the first axis (axis=0).
hstack: Combines arrays side by side (along columns).
vstack: Combines arrays on top of each other (along rows).


In [563]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

In [564]:
np.stack((array1,array2))

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [566]:
np.hstack((array1,array2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [567]:
np.vstack((array1,array2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [568]:
np.dstack((array1,array2))

array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]])

In [569]:
a=np.array([[1,2],[3,4],[5,6]])
b=np.array([[7,8],[9,10],[11,12]])

In [570]:
np.stack((a,b))

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [571]:
np.hstack((a,b))

array([[ 1,  2,  7,  8],
       [ 3,  4,  9, 10],
       [ 5,  6, 11, 12]])

In [572]:
np.vstack((a,b))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [573]:
np.dstack((a,b))

array([[[ 1,  7],
        [ 2,  8]],

       [[ 3,  9],
        [ 4, 10]],

       [[ 5, 11],
        [ 6, 12]]])

In [ ]:
#----3d---
hstack will concatenate along the second axis (columns) for each "layer" (2D slice) in the 3D array.
vstack will concatenate along the first axis (rows) for each "layer" (2D slice) in the 3D array.
hstack: Horizontally stacks 3D arrays, concatenating the columns in each "layer" (2D slice).
vstack: Vertically stacks 3D arrays, concatenating the rows in each "layer" (2D slice).


In [574]:
array1 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
array2 = np.array([[[9, 10], [11, 12]], [[13, 14], [15, 16]]])

In [578]:
array1,array2

(array([[[1, 2],
         [3, 4]],
 
        [[5, 6],
         [7, 8]]]),
 array([[[ 9, 10],
         [11, 12]],
 
        [[13, 14],
         [15, 16]]]))

In [575]:
np.stack((array1,array2))

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [576]:
np.hstack((array1,array2))

array([[[ 1,  2],
        [ 3,  4],
        [ 9, 10],
        [11, 12]],

       [[ 5,  6],
        [ 7,  8],
        [13, 14],
        [15, 16]]])

In [577]:
np.vstack((array1,array2))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]]])

In [579]:
np.dstack((array1,array2))

array([[[ 1,  2,  9, 10],
        [ 3,  4, 11, 12]],

       [[ 5,  6, 13, 14],
        [ 7,  8, 15, 16]]])

In [580]:
j=np.array(["a","b","c"])
h=np.array(["v","n","m"])

In [581]:
np.hstack((j,h))

array(['a', 'b', 'c', 'v', 'n', 'm'], dtype='<U1')

In [582]:
np.vstack((j,h))

array([['a', 'b', 'c'],
       ['v', 'n', 'm']], dtype='<U1')

In [583]:
np.dstack((j,h))

array([[['a', 'v'],
        ['b', 'n'],
        ['c', 'm']]], dtype='<U1')

In [584]:
p=np.array([["a","b"],["g","j"]])
k=np.array([["v","n"],["f","d"]])


In [585]:
np.hstack((p,k))

array([['a', 'b', 'v', 'n'],
       ['g', 'j', 'f', 'd']], dtype='<U1')

In [586]:
np.vstack((p,k))

array([['a', 'b'],
       ['g', 'j'],
       ['v', 'n'],
       ['f', 'd']], dtype='<U1')

In [587]:
np.dstack((p,k))

array([[['a', 'v'],
        ['b', 'n']],

       [['g', 'f'],
        ['j', 'd']]], dtype='<U1')

In [588]:
p=np.array([[["a","b"],["g","j"]],[["a","s"],["o","p"]]])
k=np.array([[["v","n"],["f","d"]],[["w","r"],["e","u"]]])


In [589]:
np.hstack((p,k))

array([[['a', 'b'],
        ['g', 'j'],
        ['v', 'n'],
        ['f', 'd']],

       [['a', 's'],
        ['o', 'p'],
        ['w', 'r'],
        ['e', 'u']]], dtype='<U1')

In [590]:
np.vstack((p,k))

array([[['a', 'b'],
        ['g', 'j']],

       [['a', 's'],
        ['o', 'p']],

       [['v', 'n'],
        ['f', 'd']],

       [['w', 'r'],
        ['e', 'u']]], dtype='<U1')

In [591]:
np.dstack((p,k))

array([[['a', 'b', 'v', 'n'],
        ['g', 'j', 'f', 'd']],

       [['a', 's', 'w', 'r'],
        ['o', 'p', 'e', 'u']]], dtype='<U1')

In [45]:
t=np.array([1,2,3,4,5,6,7,8,9])
t

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.array_split(t,4)

[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [603]:
p=np.array([["a","b"],["g","j"],["h","i"],["i","o"]])
p

array([['a', 'b'],
       ['g', 'j'],
       ['h', 'i'],
       ['i', 'o']], dtype='<U1')

In [604]:
np.array_split(p,3)

[array([['a', 'b'],
        ['g', 'j']], dtype='<U1'),
 array([['h', 'i']], dtype='<U1'),
 array([['i', 'o']], dtype='<U1')]

In [612]:
k=np.array([[["v","n"],["f","d"]],[["w","r"],["e","u"]],[["g","j"],["h","i"]]])
k

array([[['v', 'n'],
        ['f', 'd']],

       [['w', 'r'],
        ['e', 'u']],

       [['g', 'j'],
        ['h', 'i']]], dtype='<U1')

In [613]:
np.array_split(k,3)

[array([[['v', 'n'],
         ['f', 'd']]], dtype='<U1'),
 array([[['w', 'r'],
         ['e', 'u']]], dtype='<U1'),
 array([[['g', 'j'],
         ['h', 'i']]], dtype='<U1')]

In [47]:
arr3=np.array([[[1,2,4],[3,4,8],[9,8,7]],[[5,6,9],[7,8,10],[6,5,4]]])
arr3

array([[[ 1,  2,  4],
        [ 3,  4,  8],
        [ 9,  8,  7]],

       [[ 5,  6,  9],
        [ 7,  8, 10],
        [ 6,  5,  4]]])

In [630]:
np.hsplit(arr3,3)

[array([[[1, 2, 4]],
 
        [[5, 6, 9]]]),
 array([[[ 3,  4,  8]],
 
        [[ 7,  8, 10]]]),
 array([[[9, 8, 7]],
 
        [[6, 5, 4]]])]

In [632]:
np.vsplit(arr3,2)

[array([[[1, 2, 4],
         [3, 4, 8],
         [9, 8, 7]]]),
 array([[[ 5,  6,  9],
         [ 7,  8, 10],
         [ 6,  5,  4]]])]

In [634]:
np.dsplit(arr3,3)

[array([[[1],
         [3],
         [9]],
 
        [[5],
         [7],
         [6]]]),
 array([[[2],
         [4],
         [8]],
 
        [[6],
         [8],
         [5]]]),
 array([[[ 4],
         [ 8],
         [ 7]],
 
        [[ 9],
         [10],
         [ 4]]])]

In [635]:
p=np.array([["a","b"],["g","j"],["h","i"],["i","o"]])
p

array([['a', 'b'],
       ['g', 'j'],
       ['h', 'i'],
       ['i', 'o']], dtype='<U1')

In [637]:
np.hsplit(p,2)

[array([['a'],
        ['g'],
        ['h'],
        ['i']], dtype='<U1'),
 array([['b'],
        ['j'],
        ['i'],
        ['o']], dtype='<U1')]

In [639]:
np.vsplit(p,4)

[array([['a', 'b']], dtype='<U1'),
 array([['g', 'j']], dtype='<U1'),
 array([['h', 'i']], dtype='<U1'),
 array([['i', 'o']], dtype='<U1')]

In [640]:
np.dsplit(p,2)

ValueError: dsplit only works on arrays of 3 or more dimensions

In [641]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [643]:
np.hsplit(a,1)

[array([1, 2, 3, 4, 5])]

In [646]:
np.vsplit(a,1)

ValueError: vsplit only works on arrays of 2 or more dimensions

In [49]:
u=np.array([1,2,3,4,5,6,7,4,2,3,4,1,2,9,4])
u

array([1, 2, 3, 4, 5, 6, 7, 4, 2, 3, 4, 1, 2, 9, 4])

In [50]:
#where (index)

In [51]:
np.where(u==4)

(array([ 3,  7, 10, 14], dtype=int64),)

In [52]:
np.where(u%2==0)

(array([ 1,  3,  5,  7,  8, 10, 12, 14], dtype=int64),)

In [53]:
np.where(u>4,100,0)

array([  0,   0,   0,   0, 100, 100, 100,   0,   0,   0,   0,   0,   0,
       100,   0])

In [653]:
p=np.array([["a","i"],["g","j"],["h","i"],["i","o"]])
p

array([['a', 'i'],
       ['g', 'j'],
       ['h', 'i'],
       ['i', 'o']], dtype='<U1')

In [658]:
np.where(p=="i")

(array([0, 2, 3], dtype=int64), array([1, 1, 0], dtype=int64))

In [659]:
b=np.array([[7,8],[9,10],[11,12]])
b

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [660]:
np.where(b%2==0)

(array([0, 1, 2], dtype=int64), array([1, 1, 1], dtype=int64))

In [663]:
np.where(b>=0)

(array([0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 0, 1, 0, 1], dtype=int64))

In [664]:
np.where(b>=10)

(array([1, 2, 2], dtype=int64), array([1, 0, 1], dtype=int64))

In [666]:
g=np.array([[["i","j"],["k","l"]],[["m","n"],["o","p"]],[["m","k"],["k","p"]],[["m","n"],["o","p"]]])
g

array([[['i', 'j'],
        ['k', 'l']],

       [['m', 'n'],
        ['o', 'p']],

       [['m', 'k'],
        ['k', 'p']],

       [['m', 'n'],
        ['o', 'p']]], dtype='<U1')

In [667]:
np.where(g=="k")

(array([0, 2, 2], dtype=int64),
 array([1, 0, 1], dtype=int64),
 array([0, 1, 0], dtype=int64))

In [56]:
#search sorted
ar=np.array([7,9,8,10])
ar

array([ 7,  9,  8, 10])

In [57]:
np.searchsorted(ar,6)

0

In [58]:
np.searchsorted(ar,9)

3

In [676]:
ar

array([ 7,  9,  8, 10])

In [677]:
j=np.array([18,9,21,99])
j

array([18,  9, 21, 99])

In [678]:
np.searchsorted(j,10)

2

In [682]:
np.searchsorted(j,100)

4

In [683]:
a=np.array(["banana","cherry","apple","apricot"])
a

array(['banana', 'cherry', 'apple', 'apricot'], dtype='<U7')

In [684]:
np.sort(a)

array(['apple', 'apricot', 'banana', 'cherry'], dtype='<U7')

In [686]:
a=np.array([1,2,3,4,5,6,7,8])
x=[True,False,True,True,True,False,True,True]

In [688]:
a[x]

array([1, 3, 4, 5, 7, 8])

In [2]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8])

In [3]:
a[a%2!=0]

array([1, 3, 5, 7])

In [4]:
filtered_array=[]
for i in a:
    if i>5:
        filtered_array.append(True)
    else:
        filtered_array.append(False)

In [5]:
a[filtered_array]

array([6, 7, 8])

In [6]:
#insert,delete

In [7]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
insert(array,position,element)

In [8]:
np.insert(a,3,5)

array([1, 2, 3, 5, 4, 5, 6, 7, 8])

In [9]:
np.append(a,10)

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10])

In [10]:
b=np.array([[7,8],[9,10],[11,12]])
b

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [11]:
np.insert(b,2,[4,6],axis=0)

array([[ 7,  8],
       [ 9, 10],
       [ 4,  6],
       [11, 12]])

In [12]:
np.insert(b,0,[4,6,8],axis=1)

array([[ 4,  7,  8],
       [ 6,  9, 10],
       [ 8, 11, 12]])

In [13]:
b

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [40]:
array2

array([4, 5, 6])

In [14]:
np.insert(array2,2,[[10,20,30]],axis=0)

NameError: name 'array2' is not defined

In [714]:
np.insert(array2,1,[1,7],axis=1)

array([[[ 9, 10],
        [ 1,  7],
        [11, 12]],

       [[13, 14],
        [ 1,  7],
        [15, 16]]])

In [715]:
np.insert(array2,1,[1,7],axis=2)

array([[[ 9,  1, 10],
        [11,  7, 12]],

       [[13,  1, 14],
        [15,  7, 16]]])

# 09/10/2024

In [23]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [30]:
a=np.delete(a,3)

In [31]:
a

array([1, 2, 3, 5, 6, 7, 8])

In [32]:
a=np.delete(a,[3,4,5])

In [33]:
a

array([1, 2, 3, 8])

In [36]:
v=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
v

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [37]:
np.delete(v,[1,2],axis=0)

array([[ 1,  2,  3],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [38]:
v

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [39]:
np.delete(v,[1,2],axis=1)

array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]])

In [51]:
array2

array([4, 5, 6])

In [52]:
np.delete(array2,0,axis=0)

array([5, 6])

In [ ]:
dot:


In [40]:
a=np.array([1,2,3])
b=np.array([5,6,7])
a,b

(array([1, 2, 3]), array([5, 6, 7]))

In [41]:
np.dot(a,b)

38

In [55]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [56]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [57]:
np.matmul(a,b)

array([[19, 22],
       [43, 50]])

In [42]:
d=np.arange(16).reshape(4,4)
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [735]:
np.fliplr(d)

array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8],
       [15, 14, 13, 12]])

In [736]:
np.flipud(d)

array([[12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [59]:
np.flip(d)

array([[15, 14, 13, 12],
       [11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])

In [738]:
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [740]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [743]:
array2

array([[[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]]])

In [742]:
np.fliplr(array2)

array([[[11, 12],
        [ 9, 10]],

       [[15, 16],
        [13, 14]]])

In [744]:
np.flipud(array2)

array([[[13, 14],
        [15, 16]],

       [[ 9, 10],
        [11, 12]]])

In [745]:
np.flip(array2)

array([[[16, 15],
        [14, 13]],

       [[12, 11],
        [10,  9]]])

In [746]:
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [46]:
np.rot90(d,k=1)

array([[ 3,  7, 11, 15],
       [ 2,  6, 10, 14],
       [ 1,  5,  9, 13],
       [ 0,  4,  8, 12]])

In [44]:
array2

NameError: name 'array2' is not defined

In [753]:
np.rot90(array2,k=2)

array([[[15, 16],
        [13, 14]],

       [[11, 12],
        [ 9, 10]]])

In [754]:
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [49]:
np.roll(d,shift=3,axis=0)

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [ 0,  1,  2,  3]])

In [758]:
np.roll(d,shift=3,axis=1)

array([[ 1,  2,  3,  0],
       [ 5,  6,  7,  4],
       [ 9, 10, 11,  8],
       [13, 14, 15, 12]])

In [759]:
a=np.random.rand(10)
a

array([0.56804456, 0.92559664, 0.07103606, 0.0871293 , 0.0202184 ,
       0.83261985, 0.77815675, 0.87001215, 0.97861834, 0.79915856])

In [760]:
np.set_printoptions(precision=2)

In [761]:
a

array([0.57, 0.93, 0.07, 0.09, 0.02, 0.83, 0.78, 0.87, 0.98, 0.8 ])

In [765]:
np.random.rand(2,3)

array([[0.12, 0.64, 0.14],
       [0.94, 0.52, 0.41]])

In [772]:
a=np.arange(50000)
a

array([    0,     1,     2,     3,     4,     5,     6,     7,     8,
           9,    10,    11,    12,    13,    14,    15,    16,    17,
          18,    19,    20,    21,    22,    23,    24,    25,    26,
          27,    28,    29,    30,    31,    32,    33,    34,    35,
          36,    37,    38,    39,    40,    41,    42,    43,    44,
          45,    46,    47,    48,    49,    50,    51,    52,    53,
          54,    55,    56,    57,    58,    59,    60,    61,    62,
          63,    64,    65,    66,    67,    68,    69,    70,    71,
          72,    73,    74,    75,    76,    77,    78,    79,    80,
          81,    82,    83,    84,    85,    86,    87,    88,    89,
          90,    91,    92,    93,    94,    95,    96,    97,    98,
          99,   100,   101,   102,   103,   104,   105,   106,   107,
         108,   109,   110,   111,   112,   113,   114,   115,   116,
         117,   118,   119,   120,   121,   122,   123,   124,   125,
         126,   127,

In [770]:
import sys

In [771]:
np.set_printoptions(threshold=sys.maxsize)

In [768]:
a

array([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
         33,   34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
         44,   45,   46,   47,   48,   49,   50,   51,   52,   53,   54,
         55,   56,   57,   58,   59,   60,   61,   62,   63,   64,   65,
         66,   67,   68,   69,   70,   71,   72,   73,   74,   75,   76,
         77,   78,   79,   80,   81,   82,   83,   84,   85,   86,   87,
         88,   89,   90,   91,   92,   93,   94,   95,   96,   97,   98,
         99,  100,  101,  102,  103,  104,  105,  106,  107,  108,  109,
        110,  111,  112,  113,  114,  115,  116,  117,  118,  119,  120,
        121,  122,  123,  124,  125,  126,  127,  128,  129,  130,  131,
        132,  133,  134,  135,  136,  137,  138,  139,  140,  141,  142,
        143,  144,  145,  146,  147,  148,  149,  1

In [779]:
a=np.arange(36).reshape(6,-1)

In [780]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [51]:
import datetime

In [52]:
datetime.datetime.now()

datetime.datetime(2025, 2, 19, 16, 4, 54, 9726)

In [785]:
np.datetime64('today')

numpy.datetime64('2024-10-09')

In [54]:
np.datetime64("today","D")+np.timedelta64(5,'W')

numpy.datetime64('2025-03-26')

In [55]:
np.datetime64("today","D")-np.timedelta64(5,'D')

numpy.datetime64('2025-02-14')

In [791]:
np.arange('2024-10-01','2024-11-01',dtype="datetime64[D]")

array(['2024-10-01', '2024-10-02', '2024-10-03', '2024-10-04',
       '2024-10-05', '2024-10-06', '2024-10-07', '2024-10-08',
       '2024-10-09', '2024-10-10', '2024-10-11', '2024-10-12',
       '2024-10-13', '2024-10-14', '2024-10-15', '2024-10-16',
       '2024-10-17', '2024-10-18', '2024-10-19', '2024-10-20',
       '2024-10-21', '2024-10-22', '2024-10-23', '2024-10-24',
       '2024-10-25', '2024-10-26', '2024-10-27', '2024-10-28',
       '2024-10-29', '2024-10-30', '2024-10-31'], dtype='datetime64[D]')

In [792]:
np.arange('2024-01-01','2025-01-01',dtype="datetime64[D]")

array(['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04',
       '2024-01-05', '2024-01-06', '2024-01-07', '2024-01-08',
       '2024-01-09', '2024-01-10', '2024-01-11', '2024-01-12',
       '2024-01-13', '2024-01-14', '2024-01-15', '2024-01-16',
       '2024-01-17', '2024-01-18', '2024-01-19', '2024-01-20',
       '2024-01-21', '2024-01-22', '2024-01-23', '2024-01-24',
       '2024-01-25', '2024-01-26', '2024-01-27', '2024-01-28',
       '2024-01-29', '2024-01-30', '2024-01-31', '2024-02-01',
       '2024-02-02', '2024-02-03', '2024-02-04', '2024-02-05',
       '2024-02-06', '2024-02-07', '2024-02-08', '2024-02-09',
       '2024-02-10', '2024-02-11', '2024-02-12', '2024-02-13',
       '2024-02-14', '2024-02-15', '2024-02-16', '2024-02-17',
       '2024-02-18', '2024-02-19', '2024-02-20', '2024-02-21',
       '2024-02-22', '2024-02-23', '2024-02-24', '2024-02-25',
       '2024-02-26', '2024-02-27', '2024-02-28', '2024-02-29',
       '2024-03-01', '2024-03-02', '2024-03-03', '2024-

In [793]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [794]:
np.random.shuffle(arr)

In [795]:
arr

array([5, 1, 9, 6, 0, 8, 4, 7, 2, 3])

In [796]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [799]:
np.percentile(a,25)

2.0

In [800]:
arr1=np.array([[2,3],[4,5]])
arr1

array([[2, 3],
       [4, 5]])

In [802]:
np.percentile(arr1,50,axis=0)

array([3., 4.])

In [803]:
np.percentile(arr1,50,axis=1)

array([2.5, 4.5])

In [804]:
np.percentile(arr1,90,axis=0)

array([3.8, 4.8])

In [805]:
np.percentile(arr1,90,axis=1)

array([2.9, 4.9])

In [56]:
a=np.array([1,2,3,4,6,6,7,8,1,9,15,20,10,100])
a

array([  1,   2,   3,   4,   6,   6,   7,   8,   1,   9,  15,  20,  10,
       100])

In [57]:
np.bincount(a)

array([0, 2, 1, 1, 1, 0, 2, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], dtype=int64)

In [814]:
import pickle

In [ ]:
Protocol version 4 was added in Python 3.4. It adds support for very large objects, 
pickling more kinds of objects, and some data format optimizations. It is the default protocol starting with Python 3.8. 
Refer to PEP 3154 for information about improvements brought by protocol 4.

In [815]:
a=np.array([100,200,300])
a

array([100, 200, 300])

In [823]:
aa=pickle.dumps(a,protocol=4)
aa

b'\x80\x04\x95\x94\x00\x00\x00\x00\x00\x00\x00\x8c\x15numpy.core.multiarray\x94\x8c\x0c_reconstruct\x94\x93\x94\x8c\x05numpy\x94\x8c\x07ndarray\x94\x93\x94K\x00\x85\x94C\x01b\x94\x87\x94R\x94(K\x01K\x03\x85\x94h\x03\x8c\x05dtype\x94\x93\x94\x8c\x02i4\x94\x89\x88\x87\x94R\x94(K\x03\x8c\x01<\x94NNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00t\x94b\x89C\x0cd\x00\x00\x00\xc8\x00\x00\x00,\x01\x00\x00\x94t\x94b.'

In [825]:
pickle.loads(aa)

array([100, 200, 300])

In [828]:
np.busday_count("2024-01-01","2025-01-01")

262